// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. 
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// CardChargeDao is the data access object for table verify_card_charge.
type CardChargeDao struct {
	table   string          // table is the underlying table name of the DAO.
	group   string          // group is the database configuration group name of current DAO.
	columns CardChargeColumns // columns contains all the column names of Table for convenient usage.
}

// CardChargeColumns defines and stores column names for table verify_card_charge.
type CardChargeColumns struct {
	Id                string // 充值记录ID      
    CardCode          string // 被充值卡密      
    UseCardCode       string // 使用的卡密      
    ExpireTimeBefore  string // 充值前到期日期  
    ExpireTimeAfter   string // 充值后到期日期  
    CreateBy          string // 创建者          
    UpdateBy          string // 更新者          
    CreatedAt         string // 创建时间        
    UpdatedAt         string // 修改时间
}

//  cardChargeColumns holds the columns for table verify_card_charge.
var cardChargeColumns = CardChargeColumns{
	Id:               "id",                  
            CardCode:         "card_code",           
            UseCardCode:      "use_card_code",       
            ExpireTimeBefore: "expire_time_before",  
            ExpireTimeAfter:  "expire_time_after",   
            CreateBy:         "create_by",           
            UpdateBy:         "update_by",           
            CreatedAt:        "created_at",          
            UpdatedAt:        "updated_at",
}

// NewCardChargeDao creates and returns a new DAO object for table data access.
func NewCardChargeDao() *CardChargeDao {
	return &CardChargeDao{
		group:   "default",
		table:   "verify_card_charge",
		columns: cardChargeColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *CardChargeDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *CardChargeDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *CardChargeDao) Columns() CardChargeColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *CardChargeDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *CardChargeDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *CardChargeDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}