// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/y3512537/gf-verify-admin/internal/app/verify/service/internal/dao/internal"
)

// verifyVersionDao is the data access object for table verify_version.
// You can define custom methods on it to extend its functionality as you wish.
type verifyVersionDao struct {
	*internal.VerifyVersionDao
}

var (
	// VerifyVersion is globally public accessible object for table verify_version operations.
	VerifyVersion = verifyVersionDao{
		internal.NewVerifyVersionDao(),
	}
)

// Fill with you ideas below.
