// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/y3512537/gf-verify-admin/internal/app/verify/service/internal/dao/internal"
)

// verifyAttachmentDao is the data access object for table verify_attachment.
// You can define custom methods on it to extend its functionality as you wish.
type verifyAttachmentDao struct {
	*internal.VerifyAttachmentDao
}

var (
	// VerifyAttachment is globally public accessible object for table verify_attachment operations.
	VerifyAttachment = verifyAttachmentDao{
		internal.NewVerifyAttachmentDao(),
	}
)

// Fill with you ideas below.
