// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/y3512537/gf-verify-admin/internal/app/verify/service/internal/dao/internal"
)

// verifyDeviceDao is the data access object for table verify_device.
// You can define custom methods on it to extend its functionality as you wish.
type verifyDeviceDao struct {
	*internal.VerifyDeviceDao
}

var (
	// VerifyDevice is globally public accessible object for table verify_device operations.
	VerifyDevice = verifyDeviceDao{
		internal.NewVerifyDeviceDao(),
	}
)

// Fill with you ideas below.
