// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/y3512537/gf-verify-admin/internal/app/verify/service/internal/dao/internal"
)

// verifyCardDao is the data access object for table verify_card.
// You can define custom methods on it to extend its functionality as you wish.
type verifyCardDao struct {
	*internal.VerifyCardDao
}

var (
	// VerifyCard is globally public accessible object for table verify_card operations.
	VerifyCard = verifyCardDao{
		internal.NewVerifyCardDao(),
	}
)

// Fill with you ideas below.
