// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/y3512537/gf-verify-admin/internal/app/verify/service/internal/dao/internal"
)

// verifyCardSessionDao is the data access object for table verify_card_session.
// You can define custom methods on it to extend its functionality as you wish.
type verifyCardSessionDao struct {
	*internal.VerifyCardSessionDao
}

var (
	// VerifyCardSession is globally public accessible object for table verify_card_session operations.
	VerifyCardSession = verifyCardSessionDao{
		internal.NewVerifyCardSessionDao(),
	}
)

// Fill with you ideas below.
