// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/y3512537/gf-verify-admin/internal/app/verify/service/internal/dao/internal"
)

// internalVerifyCardUnbindDao is internal type for wrapping internal DAO implements.
type internalVerifyCardUnbindDao = *internal.VerifyCardUnbindDao

// verifyCardUnbindDao is the data access object for table verify_card_unbind.
// You can define custom methods on it to extend its functionality as you wish.
type verifyCardUnbindDao struct {
	internalVerifyCardUnbindDao
}

var (
	// VerifyCardUnbind is globally public accessible object for table verify_card_unbind operations.
	VerifyCardUnbind = verifyCardUnbindDao{
		internal.NewVerifyCardUnbindDao(),
	}
)

// Fill with you ideas below.
