// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. 
// =================================================================================

package entity

import(
"github.com/gogf/gf/v2/os/gtime"
)

// VerifyCard is the golang structure for table verify_card.
type VerifyCard struct {
    Id           int64       `json:"id"           description:"卡密ID"`                        
    SoftwareId   int64       `json:"softwareId"   description:"软件ID"`                        
    CardCode     string      `json:"cardCode"     description:"密钥"`                          
    CardValue    int         `json:"cardValue"    description:"面值"`                          
    CardType     int         `json:"cardType"     description:"1 分钟 2 小时 3 天 4 月 5 年"`  
    CardStatus   int         `json:"cardStatus"   description:"状态 1 正常 0 冻结"`            
    UnbindCount  int         `json:"unbindCount"  description:"允许解绑次数"`                  
    GenTime      *gtime.Time `json:"genTime"      description:"生成时间"`                      
    ActivateTime *gtime.Time `json:"activateTime" description:"激活时间"`                      
    ExpireTime   *gtime.Time `json:"expireTime"   description:"到期时间"`                      
    Customize    int         `json:"customize"    description:"自定义属性"`                    
    KeyPrefix    string      `json:"keyPrefix"    description:"卡密前缀"`                      
    MultiOnline  int         `json:"multiOnline"  description:"多开上限"`                      
    IsReplace    int         `json:"isReplace"    description:"顶号登录 1 是 0 否"`            
    Comment      string      `json:"comment"      description:"备注"`                          
    CreatedAt    *gtime.Time `json:"createdAt"    description:"创建时间"`                      
    UpdatedAt    *gtime.Time `json:"updatedAt"    description:"修改时间"`                      
    DeletedAt    *gtime.Time `json:"deletedAt"    description:"删除时间"`                      
}