// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. 
// =================================================================================

package entity

import(
"github.com/gogf/gf/v2/os/gtime"
)

// VerifyAttachment is the golang structure for table verify_attachment.
type VerifyAttachment struct {
    Id         int64       `json:"id"         description:""`                                     
    FileName   string      `json:"fileName"   description:"附件名"`                               
    Md5        string      `json:"md5"        description:"MD5"`                                  
    StoreType  int         `json:"storeType"  description:"1 二进制 2 直接 3 蓝奏云 4 百度网盘"`  
    OtherParam string      `json:"otherParam" description:"其他参数，用于保存网盘密码等"`         
    FilePath   string      `json:"filePath"   description:"附件存储路径"`                         
    FileSize   int64       `json:"fileSize"   description:"附件大小 byte"`                        
    FileType   string      `json:"fileType"   description:""`                                     
    Remark     string      `json:"remark"     description:"备注"`                                 
    CreatedAt  *gtime.Time `json:"createdAt"  description:"创建时间"`                             
    UpdatedAt  *gtime.Time `json:"updatedAt"  description:"修改时间"`                             
    DeletedAt  *gtime.Time `json:"deletedAt"  description:"删除时间"`                             
}