// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. 
// =================================================================================

package entity

import(
"github.com/gogf/gf/v2/os/gtime"
)

// VerifyVersion is the golang structure for table verify_version.
type VerifyVersion struct {
    Id            int64       `json:"id"            description:""`          
    SoftwareId    int64       `json:"softwareId"    description:"软件Id"`    
    VersionNumber string      `json:"versionNumber" description:"主版本号"`  
    IsPublish     int         `json:"isPublish"     description:"是否发布"`  
    AttId         int64       `json:"attId"         description:"附件Id"`    
    Comment       string      `json:"comment"       description:"版本备注"`  
    CreatedAt     *gtime.Time `json:"createdAt"     description:"创建时间"`  
    UpdatedAt     *gtime.Time `json:"updatedAt"     description:"修改时间"`  
    DeletedAt     *gtime.Time `json:"deletedAt"     description:"删除时间"`  
}