// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// VerifyCardCharge is the golang structure for table verify_card_charge.
type VerifyCardCharge struct {
	Id               int64       `json:"id"               description:"充值记录ID"`
	CardCode         string      `json:"cardCode"         description:"被充值卡密"`
	UseCardCode      string      `json:"useCardCode"      description:"使用的卡密"`
	ExpireTimeBefore *gtime.Time `json:"expireTimeBefore" description:"充值前到期日期"`
	ExpireTimeAfter  *gtime.Time `json:"expireTimeAfter"  description:"充值后到期日期"`
	CreatedAt        *gtime.Time `json:"createdAt"        description:"创建时间"`
	UpdatedAt        *gtime.Time `json:"updatedAt"        description:"修改时间"`
	DeletedAt        *gtime.Time `json:"deletedAt"        description:"删除时间"`
}
