// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// VerifyCardSession is the golang structure for table verify_card_session.
type VerifyCardSession struct {
	Id             int64       `json:"id"             description:"编号"`
	CardId         int64       `json:"cardId"         description:"卡密Id"`
	SessionTimeout *gtime.Time `json:"sessionTimeout" description:"超时时间"`
	LoginIp        string      `json:"loginIp"        description:"登录IP"`
	DeviceId       int64       `json:"deviceId"       description:"设备ID"`
	DeviceToken    string      `json:"deviceToken"    description:""`
	CreatedAt      *gtime.Time `json:"createdAt"      description:"创建时间"`
	UpdatedAt      *gtime.Time `json:"updatedAt"      description:"修改时间"`
	DeletedAt      *gtime.Time `json:"deletedAt"      description:"删除时间"`
}
