// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. 
// =================================================================================

package entity

import(
"github.com/gogf/gf/v2/os/gtime"
)

// VerifyDevice is the golang structure for table verify_device.
type VerifyDevice struct {
    Id            int64       `json:"id"            description:"设备ID"`        
    CardId        int64       `json:"cardId"        description:"卡密"`          
    DeviceCode    string      `json:"deviceCode"    description:"设备编号"`      
    DeviceName    string      `json:"deviceName"    description:"设备名称"`      
    DeviceStatus  int         `json:"deviceStatus"  description:"设备状态"`      
    LastLoginTime *gtime.Time `json:"lastLoginTime" description:"最后登录时间"`  
    LoginIp       string      `json:"loginIp"       description:"当前登录IP"`    
    CreatedAt     *gtime.Time `json:"createdAt"     description:"创建时间"`      
    UpdatedAt     *gtime.Time `json:"updatedAt"     description:"修改时间"`      
    DeletedAt     *gtime.Time `json:"deletedAt"     description:"删除时间"`      
}