// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// VerifyCardUnbind is the golang structure for table verify_card_unbind.
type VerifyCardUnbind struct {
	Id         int64       `json:"id"         description:""`
	CardId     int64       `json:"cardId"     description:"卡密ID"`
	DeviceCode string      `json:"deviceCode" description:"设备编号"`
	CreatedAt  *gtime.Time `json:"createdAt"  description:"创建时间"`
	UpdatedAt  *gtime.Time `json:"updatedAt"  description:"修改时间"`
	DeletedAt  *gtime.Time `json:"deletedAt"  description:"删除时间"`
}
