// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. 
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// VerifyCardChargeDao is the data access object for table verify_card_charge.
type VerifyCardChargeDao struct {
	table   string          // table is the underlying table name of the DAO.
	group   string          // group is the database configuration group name of current DAO.
	columns VerifyCardChargeColumns // columns contains all the column names of Table for convenient usage.
}

// VerifyCardChargeColumns defines and stores column names for table verify_card_charge.
type VerifyCardChargeColumns struct {
	Id                string // 充值记录ID      
    CardCode          string // 被充值卡密      
    UseCardCode       string // 使用的卡密      
    ExpireTimeBefore  string // 充值前到期日期  
    ExpireTimeAfter   string // 充值后到期日期  
    CreatedAt         string // 创建时间        
    UpdatedAt         string // 修改时间        
    DeletedAt         string // 删除时间
}

//  verifyCardChargeColumns holds the columns for table verify_card_charge.
var verifyCardChargeColumns = VerifyCardChargeColumns{
	Id:               "id",                  
            CardCode:         "card_code",           
            UseCardCode:      "use_card_code",       
            ExpireTimeBefore: "expire_time_before",  
            ExpireTimeAfter:  "expire_time_after",   
            CreatedAt:        "created_at",          
            UpdatedAt:        "updated_at",          
            DeletedAt:        "deleted_at",
}

// NewVerifyCardChargeDao creates and returns a new DAO object for table data access.
func NewVerifyCardChargeDao() *VerifyCardChargeDao {
	return &VerifyCardChargeDao{
		group:   "default",
		table:   "verify_card_charge",
		columns: verifyCardChargeColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *VerifyCardChargeDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *VerifyCardChargeDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *VerifyCardChargeDao) Columns() VerifyCardChargeColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *VerifyCardChargeDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *VerifyCardChargeDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *VerifyCardChargeDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}