// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. 
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// VerifyAttachmentDao is the data access object for table verify_attachment.
type VerifyAttachmentDao struct {
	table   string          // table is the underlying table name of the DAO.
	group   string          // group is the database configuration group name of current DAO.
	columns VerifyAttachmentColumns // columns contains all the column names of Table for convenient usage.
}

// VerifyAttachmentColumns defines and stores column names for table verify_attachment.
type VerifyAttachmentColumns struct {
	Id          string //                                      
    FileName    string // 附件名                               
    Md5         string // MD5                                  
    StoreType   string // 1 二进制 2 直接 3 蓝奏云 4 百度网盘  
    OtherParam  string // 其他参数，用于保存网盘密码等         
    FilePath    string // 附件存储路径                         
    FileSize    string // 附件大小 byte                        
    FileType    string //                                      
    Remark      string // 备注                                 
    CreatedAt   string // 创建时间                             
    UpdatedAt   string // 修改时间                             
    DeletedAt   string // 删除时间
}

//  verifyAttachmentColumns holds the columns for table verify_attachment.
var verifyAttachmentColumns = VerifyAttachmentColumns{
	Id:         "id",           
            FileName:   "file_name",    
            Md5:        "md5",          
            StoreType:  "store_type",   
            OtherParam: "other_param",  
            FilePath:   "file_path",    
            FileSize:   "file_size",    
            FileType:   "file_type",    
            Remark:     "remark",       
            CreatedAt:  "created_at",   
            UpdatedAt:  "updated_at",   
            DeletedAt:  "deleted_at",
}

// NewVerifyAttachmentDao creates and returns a new DAO object for table data access.
func NewVerifyAttachmentDao() *VerifyAttachmentDao {
	return &VerifyAttachmentDao{
		group:   "default",
		table:   "verify_attachment",
		columns: verifyAttachmentColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *VerifyAttachmentDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *VerifyAttachmentDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *VerifyAttachmentDao) Columns() VerifyAttachmentColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *VerifyAttachmentDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *VerifyAttachmentDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *VerifyAttachmentDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}