// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// VerifyCardUnbindDao is the data access object for table verify_card_unbind.
type VerifyCardUnbindDao struct {
	table   string                  // table is the underlying table name of the DAO.
	group   string                  // group is the database configuration group name of current DAO.
	columns VerifyCardUnbindColumns // columns contains all the column names of Table for convenient usage.
}

// VerifyCardUnbindColumns defines and stores column names for table verify_card_unbind.
type VerifyCardUnbindColumns struct {
	Id         string //
	CardId     string // 卡密ID
	DeviceCode string // 设备编号
	CreatedAt  string // 创建时间
	UpdatedAt  string // 修改时间
	DeletedAt  string // 删除时间
}

//  verifyCardUnbindColumns holds the columns for table verify_card_unbind.
var verifyCardUnbindColumns = VerifyCardUnbindColumns{
	Id:         "id",
	CardId:     "card_id",
	DeviceCode: "device_code",
	CreatedAt:  "created_at",
	UpdatedAt:  "updated_at",
	DeletedAt:  "deleted_at",
}

// NewVerifyCardUnbindDao creates and returns a new DAO object for table data access.
func NewVerifyCardUnbindDao() *VerifyCardUnbindDao {
	return &VerifyCardUnbindDao{
		group:   "default",
		table:   "verify_card_unbind",
		columns: verifyCardUnbindColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *VerifyCardUnbindDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *VerifyCardUnbindDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *VerifyCardUnbindDao) Columns() VerifyCardUnbindColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *VerifyCardUnbindDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *VerifyCardUnbindDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *VerifyCardUnbindDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
