// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// VerifyCardUnbind is the golang structure of table verify_card_unbind for DAO operations like Where/Data.
type VerifyCardUnbind struct {
	g.Meta     `orm:"table:verify_card_unbind, do:true"`
	Id         interface{} //
	CardId     interface{} // 卡密ID
	DeviceCode interface{} // 设备编号
	CreatedAt  *gtime.Time // 创建时间
	UpdatedAt  *gtime.Time // 修改时间
	DeletedAt  *gtime.Time // 删除时间
}
