// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. 
// =================================================================================

package do

import(
"github.com/gogf/gf/v2/frame/g"
"github.com/gogf/gf/v2/os/gtime"
)

// VerifySoftware is the golang structure of table verify_software for DAO operations like Where/Data.
type VerifySoftware struct {
g.Meta `orm:"table:verify_software, do:true"`
    Id interface{} // 软件id                  
    SoftwareName interface{} // 软件名称                
    SecretId interface{} // 软件唯一标识            
    SecretKey interface{} // 软件密钥                
    SoftwareStatus interface{} // 软件状态                
    CardLength interface{} // 密钥长度                
    EncryptType interface{} // 加密方式 AES RSA MD5    
    KeyPrefix interface{} // 密钥前缀                
    MultiOnline interface{} // 设备上限                
    IsReplace interface{} // 是否顶号登录 1 是 0 否  
    Heartbeat interface{} // 心跳间隔                
    OpenTrial interface{} // 开启试用 1 是 0 否      
    TrialCount interface{} // 试用次数                
    TrialTime interface{} // 试用时间(分钟)          
    TrialDuration interface{} // 每次试用间隔            
    Comment interface{} // 软件备注                
    CreatedAt      *gtime.Time // 创建时间                
    UpdatedAt      *gtime.Time // 修改时间                
    DeletedAt      *gtime.Time // 删除时间                
}