// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. 
// =================================================================================

package do

import(
"github.com/gogf/gf/v2/frame/g"
"github.com/gogf/gf/v2/os/gtime"
)

// VerifyDevice is the golang structure of table verify_device for DAO operations like Where/Data.
type VerifyDevice struct {
g.Meta `orm:"table:verify_device, do:true"`
    Id interface{} // 设备ID        
    CardId interface{} // 卡密          
    DeviceCode interface{} // 设备编号      
    DeviceName interface{} // 设备名称      
    DeviceStatus interface{} // 设备状态      
    LastLoginTime *gtime.Time // 最后登录时间  
    LoginIp interface{} // 当前登录IP    
    CreatedAt     *gtime.Time // 创建时间      
    UpdatedAt     *gtime.Time // 修改时间      
    DeletedAt     *gtime.Time // 删除时间      
}